# Generated by Django 5.0.6 on 2024-07-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oss', '0011_rename_keywords_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('year', models.IntegerField(max_length=4)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.volume')),
            ],
        ),
    ]
