# Generated by Django 5.0.6 on 2024-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='year',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
