# Generated by Django 5.0.6 on 2024-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0002_alter_volume_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='year',
            field=models.IntegerField(),
        ),
    ]
