# Generated by Django 5.0.6 on 2024-07-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0004_volume_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='created_at',
        ),
    ]
