# Generated by Django 5.0.6 on 2024-07-12 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_status', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Editor_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.editor')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer_Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('manuscript_id', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('is_funded', models.BooleanField(default=False)),
                ('no_of_figures', models.IntegerField()),
                ('no_of_tables', models.IntegerField()),
                ('no_of_words', models.IntegerField()),
                ('is_submitted_already', models.BooleanField(default=False)),
                ('acknowledgement_1', models.BooleanField(default=False)),
                ('acknowledgement_2', models.BooleanField(default=False)),
                ('acknowledgement_3', models.BooleanField(default=False)),
                ('conflict_of_interest', models.BooleanField(default=False)),
                ('coi_describe', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submitted_on', models.DateField(auto_now_add=True)),
                ('decissioned_on', models.DateField(auto_now_add=True, null=True)),
                ('is_decissioned', models.BooleanField(default=False)),
                ('final_file', models.FileField(upload_to='submissions/')),
                ('admin_commments', models.TextField()),
                ('article_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.article_status')),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.article_type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.category')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.decision')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.journal')),
                ('parent_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_submissions', to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer_Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('expiring_date', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='communications/')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='AE_Assingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ae_recommendation', models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('MIN_R', 'Minimum Revision'), ('MAJ_R', 'Major Revision')], max_length=5)),
                ('ae_comments', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('file_size', models.FloatField()),
                ('file_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.file_category')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('completion_on', models.DateTimeField(blank=True, null=True)),
                ('accepted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('review_recommendation', models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('MIN_R', 'Minimum Revision'), ('MAJ_R', 'Major Revision')], max_length=5)),
                ('review_comments', models.TextField()),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.request_status')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
    ]
