# Generated by Django 5.0.6 on 2024-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0003_alter_submission_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_type',
            name='article_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
