# Generated by Django 5.0.6 on 2024-07-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0005_funder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission'),
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
    ]
