# Generated by Django 5.0.6 on 2024-07-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0006_alter_funder_submission_coauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
