# Generated by Django 5.0.6 on 2024-07-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0008_alter_coauthor_email_alter_coauthor_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='grant_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funder',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funder',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.submission'),
        ),
    ]
