# Generated by Django 5.0.6 on 2024-07-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0009_alter_funder_grant_number_alter_funder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='grant_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funder',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funder',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission'),
        ),
    ]
