# Generated by Django 5.0.6 on 2024-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0012_alter_submission_is_funded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='conflict_of_interest',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_submitted_already',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
