# Generated by Django 5.0.6 on 2024-07-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0013_alter_submission_conflict_of_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_file', models.FileField(upload_to='submissions/')),
                ('typeset_file', models.FileField(upload_to='submissions/')),
                ('corrected_title', models.CharField(blank=True, max_length=255, null=True)),
                ('corrected_abstract', models.TextField(blank=True, null=True)),
                ('corrected_on', models.DateField()),
                ('typeseted_on', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
    ]
