# Generated by Django 5.0.6 on 2024-07-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0014_accepted_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='admin_commments',
            new_name='admin_comments',
        ),
    ]
